### ISSUE TITLE
Same style of playlist

### ISSUE THREAD

**Issue by a1waysbeta** [Wil-B/Library-Tree#2]
Will you be developing a new set of playlists or playlist managers in the same style?

**Comment by Wil-B** [comment]
Sorry, but I don't have the time + I'm satisfied with the playlists already out there. A number of themes that already use Library Tree already have playlists that match sufficiently, e.g. [Georgia-REBORN](https://github.com/TT-ReBORN/Georgia-ReBORN) & Georgia use a playlist based on Catrox (The Qwertiest) that's flexible now. There's also [Eole](https://github.com/Ottodix/Eole-foobar-theme) that's using Library Tree integrated with  a playlist by Br3tt (aka falstaff). So there are already integrated solutions that can just be installed and used.
